apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kubernetes-training-producer-route
spec:
  hosts:
    - kubernetes-training-producer
  http:
    - route:
        - destination:
            host: kubernetes-training-producer
            subset: v1
          weight: 80
        - destination:
            host: kubernetes-training-producer
            subset: v2
          weight: 20
#      fault:
#        delay:
#          percentage:
#            value: 33
#          fixedDelay: 3s