apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-training-consumer
  labels:
    app: kubernetes-training-consumer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-training-consumer
  template:
    metadata:
      labels:
        app: kubernetes-training-consumer
        version: v1
    spec:
      containers:
        - name: kubernetes-training-consumer
          image: asocha/kubernetes-training-consumer:0.0.11-SNAPSHOT
          ports:
            - containerPort: 8081
          env:
            - name: PRODUCER_HOST
              value: "kubernetes-training-producer"
            - name: PRODUCER_PORT
              value: "8081"