kubernetes-training-producer:
  host: ${KUBERNETES_TRAINING_PRODUCER_PORT_8081_TCP_ADDR:localhost}
  port: ${KUBERNETES_TRAINING_PRODUCER_PORT_8081_TCP_PORT:8081}

random-number-service:
  ribbon:
    listOfServers: http://${kubernetes-training-producer.host}:${kubernetes-training-producer.port}