kubernetes-training-producer:
  host: ${PRODUCER_HOST:localhost}
  port: ${PRODUCER_PORT:8081}

producer-service:
  ribbon:
    listOfServers: "kubernetes-training-producer:8081"

configmap:
  property: "I am the local property"